
path: C:\Users\Abzsorb\Desktop\Mini-mapObjectDetection\screenshots\20240530_191933
train: Images/train
val: Images/val
test: /test

nc: 8

names: ['top', 'top_left', 'top_right', 'left', 'right', 'bottom', 'bottom_left' 'bottom_right']