
path: E:\Mini-mapObjectDetection\dataset\object_detection\TestCase5
train: Images/train
val: Images/val
test: Images/test

nc: 8

names: ['top', 'top_rights', 'top_right', 'left', 'right', 'bottom', 'bottom_left' 'bottom_right']